apiVersion: v1
kind: LimitRange
metadata:
  name: limitando-recursos
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 100Mi
    defaultRequest:
      cpu: 500m
      memory: 80Mi
    type: Container

