apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap-file
  namespace: default
spec:
  containers:
  - image: busybox
    name: busybox-configmap
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /etc/frutas
        name: meu-configmap-vol
  volumes:
  - name: meu-configmap-vol
    configMap:
      name: cores-frutas