apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
  namespace: default
  labels:
    name: primeiro-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/giropops
    server: 192.168.1.104
    readOnly: false


